### ISSUE TITLE
Preset does not consider `update.enabled: false`

### ISSUE THREAD

**Issue by bhundven-axon** [aquaproj/aqua-renovate-config#722]
Previously I had requested pinning versions, and we implemented that with:

```yaml
  - name: kubernetes-sigs/kustomize@kustomize/v5.2.1
    update:
      enabled: false
```

But this renovate preset does not seem to respect that, and I'm seeing renovate open PRs for newer versions when `update.enabled: false`.
